# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/59a560c0-1ddb-447e-a99b-3d9d1235ea4e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."rivamar:data".device = "/dev/disk/by-uuid/b04bbd0e-209e-4b1f-a55c-163afe448a5a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CA7-147C";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
